# Generated by Django 4.1.6 on 2023-02-01 20:30

from django.db import migrations, models

import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSearchableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_char_field', encrypted_json_fields.fields.EncryptedCharField()),
                ('char_field', encrypted_json_fields.fields.EncryptedSearchField(blank=True, encrypted_field_name='enc_char_field', max_length=68, null=True, salt='1234')),
                ('enc_date_field', encrypted_json_fields.fields.EncryptedDateField(null=True)),
                ('date_field', encrypted_json_fields.fields.EncryptedSearchField(blank=True, encrypted_field_name='enc_date_field', max_length=68, null=True, salt='xyz')),
                ('enc_integer_field', encrypted_json_fields.fields.EncryptedIntegerField(null=True)),
                ('integer_field', encrypted_json_fields.fields.EncryptedSearchField(blank=True, encrypted_field_name='enc_integer_field', max_length=68, null=True)),
            ],
        ),
    ]
