# Generated by Django 4.1.6 on 2023-02-13 16:24

import django.core.serializers.json
from django.db import migrations, models
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testsearchablemodel_alter_testmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='enc_json_field',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, crypter=None, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
